import type { Coffee } from "../domain/coffee";

const grinds = ["whole-bean", "filter", "aeropress", "espresso"] as const;
const image = (slug: string, name: string) =>
  [
    { src: `/images/coffees/${slug}.webp`, alt: `A bag of ${name} coffee beside roasted beans` },
  ] as const;

export const coffees = [
  {
    id: "coffee-nyeri-gichathaini",
    slug: "nyeri-gichathaini",
    name: "Gichathaini",
    status: "available",
    featuredRank: 1,
    origin: { country: "Kenya", region: "Nyeri", locality: "Gichathaini" },
    producer: "Gichathaini Factory smallholder members",
    altitudeMetres: [1700, 1900],
    varieties: ["SL28", "SL34", "Ruiru 11"],
    process: "Washed",
    harvest: "2025 main crop",
    roastIntent: "A light filter roast that keeps the fruit vivid and the finish clean.",
    taste: {
      summary: "Bright red fruit, juicy citrus and a black-tea finish.",
      notes: ["redcurrant", "pomelo", "black tea"],
      characters: ["fruit-forward", "floral"],
      brightness: 5,
      body: 2,
    },
    brewMethods: ["filter", "immersion"],
    story: {
      place:
        "Small plots around the Mathira highlands deliver ripe cherry to the Gichathaini wet mill.",
      process: "The coffee is depulped, fermented, washed and slowly dried on raised tables.",
      roast: "A restrained development keeps the citrus clear without thinning the cup.",
      cup: "Expect redcurrant brightness, pomelo sweetness and a tea-like finish.",
    },
    sizes: [
      { grams: 250, price: { currency: "MYR", amount: 6800 } },
      { grams: 1000, price: { currency: "MYR", amount: 24400 } },
    ],
    compatibleGrinds: grinds,
    subscriptionEligible: true,
    relatedGuideSlugs: ["v60-clear-sweet"],
    images: image("nyeri-gichathaini", "Gichathaini"),
  },
  {
    id: "coffee-huila-el-paraiso",
    slug: "huila-el-paraiso",
    name: "El Paraíso",
    status: "available",
    featuredRank: 2,
    origin: { country: "Colombia", region: "Huila", locality: "Acevedo" },
    producer: "Lucía Perdomo",
    altitudeMetres: [1750, 1850],
    varieties: ["Pink Bourbon"],
    process: "Washed",
    harvest: "2025 fly crop",
    roastIntent: "Balanced for filter and modern espresso, preserving floral aromatics.",
    taste: {
      summary: "Soft florals, ripe peach and a panela-like sweetness.",
      notes: ["peach", "orange blossom", "panela"],
      characters: ["floral", "fruit-forward", "sweet"],
      brightness: 4,
      body: 3,
    },
    brewMethods: ["filter", "espresso"],
    story: {
      place: "El Paraíso sits above Acevedo, where cool nights slow cherry ripening.",
      process: "Ripe Pink Bourbon is fermented in cherry, then depulped, washed and shade dried.",
      roast: "Gentle heat protects the perfume while building enough sweetness for espresso.",
      cup: "Peach and orange blossom open into a rounded panela finish.",
    },
    sizes: [
      { grams: 250, price: { currency: "MYR", amount: 7400 } },
      { grams: 1000, price: { currency: "MYR", amount: 26800 } },
    ],
    compatibleGrinds: grinds,
    subscriptionEligible: true,
    relatedGuideSlugs: ["v60-clear-sweet", "espresso-balanced-shot"],
    images: image("huila-el-paraiso", "El Paraíso"),
  },
  {
    id: "coffee-kintamani-sukawana",
    slug: "kintamani-sukawana",
    name: "Sukawana",
    status: "available",
    featuredRank: 3,
    origin: { country: "Indonesia", region: "Bali", locality: "Kintamani" },
    producer: "Sukawana community lots",
    altitudeMetres: [1200, 1450],
    varieties: ["S795", "Kartika"],
    process: "Natural",
    harvest: "2025",
    roastIntent: "A medium-light roast with a plush body and tidy fermented fruit.",
    taste: {
      summary: "Plum jam, cacao nib and warming clove.",
      notes: ["plum jam", "cacao nib", "clove"],
      characters: ["fruit-forward", "chocolatey", "spiced"],
      brightness: 3,
      body: 4,
    },
    brewMethods: ["immersion", "espresso"],
    story: {
      place: "Coffee grows among citrus and shade trees on Kintamani's volcanic slopes.",
      process:
        "Whole cherries are sorted, dried slowly and turned often for an even natural process.",
      roast: "The profile rounds the fruit and cacao while keeping the clove note in check.",
      cup: "A full, jammy cup with cacao depth and gentle spice.",
    },
    sizes: [
      { grams: 250, price: { currency: "MYR", amount: 5800 } },
      { grams: 1000, price: { currency: "MYR", amount: 20800 } },
    ],
    compatibleGrinds: grinds,
    subscriptionEligible: true,
    relatedGuideSlugs: ["aeropress-everyday-cup", "espresso-balanced-shot"],
    images: image("kintamani-sukawana", "Sukawana"),
  },
  {
    id: "coffee-guji-haro-wachhu",
    slug: "guji-haro-wachhu",
    name: "Haro Wachhu",
    status: "low-stock",
    featuredRank: 4,
    origin: { country: "Ethiopia", region: "Guji", locality: "Uraga" },
    producer: "Haro Wachhu smallholder contributors",
    altitudeMetres: [2100, 2300],
    varieties: ["JARC selections", "local landraces"],
    process: "Washed",
    harvest: "2025",
    roastIntent: "Very light and soluble for aromatic filter brewing.",
    taste: {
      summary: "Jasmine, bergamot and a light apricot sweetness.",
      notes: ["jasmine", "bergamot", "apricot"],
      characters: ["floral", "fruit-forward"],
      brightness: 5,
      body: 1,
    },
    brewMethods: ["filter"],
    story: {
      place: "High-elevation gardens around Uraga produce dense, slowly ripened cherry.",
      process: "Cherry is hand sorted, washed and dried in thin layers on raised beds.",
      roast: "A short, careful profile keeps the florals open and the texture delicate.",
      cup: "Jasmine and bergamot lead, with apricot sweetness underneath.",
    },
    sizes: [
      { grams: 250, price: { currency: "MYR", amount: 7800 } },
      { grams: 1000, price: { currency: "MYR", amount: 28400 } },
    ],
    compatibleGrinds: ["whole-bean", "filter", "aeropress"],
    subscriptionEligible: true,
    relatedGuideSlugs: ["v60-clear-sweet"],
    images: image("guji-haro-wachhu", "Haro Wachhu"),
  },
  {
    id: "coffee-sabah-kundasang",
    slug: "sabah-kundasang",
    name: "Kundasang",
    status: "available",
    featuredRank: 5,
    origin: { country: "Malaysia", region: "Sabah", locality: "Kundasang" },
    producer: "Mesilau Hills grower group",
    altitudeMetres: [1100, 1350],
    varieties: ["Catimor", "Typica"],
    process: "Honey",
    harvest: "2025",
    roastIntent: "Developed for sweetness, gentle acidity and an easy everyday brew.",
    taste: {
      summary: "Palm sugar, dried fig and toasted almond.",
      notes: ["palm sugar", "dried fig", "toasted almond"],
      characters: ["sweet", "chocolatey"],
      brightness: 2,
      body: 4,
    },
    brewMethods: ["filter", "immersion", "espresso"],
    story: {
      place: "Small hillside plots face cool mornings near Mount Kinabalu.",
      process:
        "Part of the fruit mucilage remains during drying, building sweetness without heavy fermentation.",
      roast: "A slightly longer development brings out palm sugar and almond.",
      cup: "Comforting sweetness, dried-fruit depth and a rounded finish.",
    },
    sizes: [
      { grams: 250, price: { currency: "MYR", amount: 5200 } },
      { grams: 1000, price: { currency: "MYR", amount: 18800 } },
    ],
    compatibleGrinds: grinds,
    subscriptionEligible: true,
    relatedGuideSlugs: ["aeropress-everyday-cup", "espresso-balanced-shot"],
    images: image("sabah-kundasang", "Kundasang"),
  },
  {
    id: "coffee-antigua-la-labor",
    slug: "antigua-la-labor",
    name: "La Labor",
    status: "available",
    featuredRank: 6,
    origin: { country: "Guatemala", region: "Antigua", locality: "San Miguel Dueñas" },
    producer: "Familia Cifuentes",
    altitudeMetres: [1500, 1700],
    varieties: ["Bourbon", "Caturra"],
    process: "Washed",
    harvest: "2025",
    roastIntent: "A composed omni roast with caramel sweetness and cocoa structure.",
    taste: {
      summary: "Red apple, caramel and cocoa with a round finish.",
      notes: ["red apple", "caramel", "cocoa"],
      characters: ["sweet", "chocolatey", "fruit-forward"],
      brightness: 3,
      body: 4,
    },
    brewMethods: ["filter", "immersion", "espresso"],
    story: {
      place: "Volcanic soils and sheltered afternoons shape this Antigua lot.",
      process: "Cherry is depulped, fermented overnight, washed and patio dried.",
      roast: "Measured development builds caramel and cocoa without muting the apple note.",
      cup: "Round and familiar, with red apple lift and a cocoa finish.",
    },
    sizes: [
      { grams: 250, price: { currency: "MYR", amount: 6000 } },
      { grams: 1000, price: { currency: "MYR", amount: 21600 } },
    ],
    compatibleGrinds: grinds,
    subscriptionEligible: true,
    relatedGuideSlugs: ["aeropress-everyday-cup", "espresso-balanced-shot"],
    images: image("antigua-la-labor", "La Labor"),
  },
  {
    id: "coffee-rwanda-nyamasheke",
    slug: "rwanda-nyamasheke",
    name: "Nyamasheke",
    status: "sold-out",
    featuredRank: null,
    origin: { country: "Rwanda", region: "Western Province", locality: "Nyamasheke" },
    producer: "Kivubelt washing station contributors",
    altitudeMetres: [1600, 1950],
    varieties: ["Red Bourbon"],
    process: "Washed",
    harvest: "2024",
    roastIntent: "A clear filter roast balancing citrus and brown-sugar sweetness.",
    taste: {
      summary: "Mandarin, raisin and brown sugar.",
      notes: ["mandarin", "raisin", "brown sugar"],
      characters: ["fruit-forward", "sweet"],
      brightness: 4,
      body: 3,
    },
    brewMethods: ["filter", "immersion"],
    story: {
      place: "Hillside farms overlook Lake Kivu in Rwanda's Western Province.",
      process: "Careful flotation, washing and raised-bed drying produced a clean lot.",
      roast: "The roast kept mandarin brightness while building brown-sugar sweetness.",
      cup: "Mandarin and raisin with a soft, sweet finish.",
    },
    sizes: [
      { grams: 250, price: { currency: "MYR", amount: 6200 } },
      { grams: 1000, price: { currency: "MYR", amount: 22400 } },
    ],
    compatibleGrinds: ["whole-bean", "filter", "aeropress"],
    subscriptionEligible: false,
    relatedGuideSlugs: ["v60-clear-sweet"],
    images: image("rwanda-nyamasheke", "Nyamasheke"),
  },
] as const satisfies readonly Coffee[];

export function getCoffeeBySlug(slug: string): Coffee | undefined {
  return coffees.find((coffee) => coffee.slug === slug);
}
